development:
  adapter: postgresql
  encoding: unicode
  database: db_explorer

test:
  adapter: postgresql
  encoding: unicode
  database: db_explorer_test

production:
  adapter: postgresql
  encoding: unicode
  database: db_explorer
